### ISSUE TITLE
shairport-sync 2.1.15 doesn't build

### ISSUE THREAD

**Issue by MohammadAG** [mikebrady/shairport-sync-for-openwrt#10]
I realize this may be an "unsupported" issue, but when pointing the Makefile to 2.1.15, shairport-sync fails to build because libpopt is missing, 2.1.12 builds fine.

Here's the configure log (or where it fails actually):
checking for POPT... no
configure: error: Package requirements (popt) were not met:

No package 'popt' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables POPT_CFLAGS
and POPT_LIBS to avoid the need to call pkg-config.

libpopt is selected in menuconfig, and I also added it as a build depdency

**Comment by MohammadAG** [comment]
Reverting https://github.com/mikebrady/shairport-sync/commit/1f759e57e8c0682613eaaf89a46fdf6db4c6b5cd fixes this.

**Comment by mikebrady** [comment]
Let me check it. My recollection is that pointing to 2.1.15 and building from a fresh download of OpenWrt trunk worked fine. 
[Edit] I can reproduce this error – it might take me a while to figure out where the problem is, meantime your workaround is fine. Thanks for the report.

**Comment by mikebrady** [comment]
It turns out that problem is the version of `libpopt` in OpenWrt trunk is pretty old – 1.7 – and doesn't support PKG_CONFIG, while the current version – 1.16 – does. I won't be able to offer a patch for about two weeks, but that's the issue.

**Comment by mikebrady** [comment]
This issue is fixed – the `popt` library has been updated on trunk. See https://dev.openwrt.org/changeset/43994.
