### ISSUE TITLE
Configure for pulseaudio backend support

### ISSUE THREAD

**Issue by flxkrmr** [mikebrady/shairport-sync-for-openwrt#12]
Do you have any experience with this in an openwrt buildroot?

I've tried adding the appropriate configure arguments to the Makefile, but it seems that libpulse-simple is missing. (`checking for pa_simple_new in -lpulse-simple... no`)
I have installed the pulseaudio package from openwrt and added `+libpulse-simple` to the dependencies in the Makefile. As I don't know the right name of the dependency (or if it even excists in my buildroot), I've also tried `+libpulse` and `+libpulseaudio`, but this didn't make a difference.

**Comment by mikebrady** [comment]
Hi. Thanks for your interest. I don't have much experience with pulseaudio. However, in Open Wrt, it looks like the package is called `pulseaudio-daemon`. Is it worth adding `+pulseaudio-daemon`? (Sorry, but I can't check it right away.)

**Comment by flxkrmr** [comment]
Thanks for the fast reply. Unfortunately it didn't help. 
The main reason I wanted to use pulseaudio, was the software mix feature (in addition to that, its network streaming functions are also nice to have), but as I encountered a few more problems compiling other software for pulseaudio, I'll use the ALSA dmix plugin for now. I think this is the easiest solutio for my use case. Still thanks for your help!

**Comment by mikebrady** [comment]
Fair enough. I'll close the issue for now. Just FYI, I've never tried to get Shairport  Sync to work with PulseAudio because I can't see how to make a pulseaudio back end provide latency information back to Shairport Sync. So even if you got it compiling properly, it might still not work... Some day, maybe...
