### ISSUE TITLE
New Version of shairport-sync 2.6 on Openwrt

### ISSUE THREAD

**Issue by atze09** [mikebrady/shairport-sync-for-openwrt#13]
Hello Mike,
Because of i had the issue with my Synology Nas with the "old" shairport sync version i would like to know if there is a way to update the shairport sync version for Openwert to 2.6.

Can i do this on my own? If yes how?

Or do you have to update this?

Thank you in advance.

Best Regards,
Dominik

**Comment by mikebrady** [comment]
Hi Dominik, and thanks for your interest in Shairport Sync. Can I ask a couple of quick questions please: first, did you install it from this shairport-sync-for-openwrt repository? and second, what version of OpenWrt are you using? I ask these questions because there is a nice new package in trunk for Shairport Sync.

**Comment by atze09** [comment]
Hello Mike,
and thank you for your quick reply.
I have folled this tutorial:

https://tlwr710nprojects.wordpress.com/2015/06/07/der-tl-wr710n-als-airplay-client/

Which nice New package do you mean? Do you have a link?

Besteht regards,
Dominik

**Comment by atze09** [comment]
I think now i saw what you mean.
https://github.com/openwrt/packages/tree/master/sound/shairport-sync
Seems your shairport-sync is now official package of openwrt, isn't it?
That's awesome, i really like your work!

**Comment by mikebrady** [comment]
Thanks for your kind words. You beat me to the reply.

If you are happy to update to the latest OpenWrt, what you should do is
1. note your Shairport Sync settings, such as name, output device, mixer name, 'stuffing' setting, password, etc.
2. remove the `shairport-sync-for-openwrt` folder from the packages folder of your OpenWrt folder.

Update to the latest OpenWrt and then, as follows, update the package feeds:

```
 ./scripts/feeds update -a
```

You can search for Shairport Sync and install its new package. Here's a search:

```
$./scripts/feeds search shairport
Search results in feed 'packages':
shairplay                   Shairplay
shairport                   ShairPort AirPort Express emulator (un-maintained)
shairport-sync-mini         AirPlay compatible audio player (minimal)
shairport-sync-openssl      AirPlay compatible audio player (openssl)
shairport-sync-polarssl     AirPlay compatible audio player (polarssl)
Search results in feed 'luci':
luci-app-shairport          LuCI Support for Shairport
```

Remember then to select the appropriate version of it using `make menuconfig`. I recommend the `shairport-sync-openssl` package unless you are trying to do something special.

If you are installing just the Shairport Sync package into the old, existing, OpenWrt system without upgrading OpenWrt itself, then:
1. remove the file `/etc/init.d/shairport-sync`
2. remove the file `/etc/config/shairport-sync`
3. Install Shairport Sync.

It will install a new /etc/config/shairport-sync file into which you'll have to put your settings. Make sure to remove the line that disables the use of the settings stanza.

Note that you may run into trouble if Shairport Sync relies on stuff that isn't in the older OpenWrt system –  you may get dependency errors, and you may need to install a few other packages, or it might be that you have to update OpenWrt itself too, YMMV.

**Comment by atze09** [comment]
Thank you very much Mike, you're awesome.
I am currently awaiting my OpenWRT Router will will try your suggestions and reply.
I think we can close this here

**Comment by atze09** [comment]
Hello Mike,
shairport-sync automatically comes with the chaos calmer openwrt version and i successfully installed it.
But it is the old version, where i have issues with my synology.
Unfortunately i had no success in building my own openwrt.
Maybe you can give me a short tutorial how to upgrade shairport sync to 2.6.
That would be awesome.
Thank you in advance.

Best Regards,
Dominik

**Comment by atze09** [comment]
Hello Mike,
Can you help me on this topic?
Need to update the shairport to 2.6
Thanks in advance
Best Regards,
Dominik

**Comment by mikebrady** [comment]
Sure thing, but I'm away on business until next week...

**Comment by atze09** [comment]
No hurry, enjoy your trip.

**Comment by mikebrady** [comment]
Hi there. I've created a new branch called `barrier-breaker` and it should also work with Chaos Calmer. Could you give it a try and let me know (the instructions have been updated).

**Comment by atze09** [comment]
Hello Mike,
Thank you for your answer.
But do i really need to build a new firmware.
Isn't it possible to update the shairport version on running openwrt?

I wasn't successful in building my own version.
Can anyone provide me a openwrt version for wr710n (ar71xx chipset) with shairport version 2.6.
That would be awesome.

Best Regards,
Dominik

**Comment by mikebrady** [comment]
Hi Dominik. When the new firmware image is built, separate packages for `shairport-sync` and for `libsoxr` are also built, and you'll find them in `bin/ar71xx/packages/base`. You don't actually need to install the complete new image, just the `shairport-sync` and `libsoxr` packages.

**Comment by atze09** [comment]
Thank you Mike,
but my build system seems to be broken.
I cannot build it, maybe anyone can provide me the two packages??

**Comment by mikebrady** [comment]
Can you tell me the exact version of the Shairport Sync that's in your Synology system at present please? If you enter `shairport-sync -V` you'll get a version string.

**Comment by mikebrady** [comment]
Send me an email and I can send you back the packages.

**Comment by atze09** [comment]
Thank you, 
my Email is ds1707@gmx.net.
I do not have the package installed on my synology.
Synology is my server and the shairport-sync are my clients (on Raspberrys and WR710N)
I have problem playing from synology with "2.1.15-openssl-Avahi-ALSA-soxr" Version installe on WR710N.
Would be awesome if you could send me those packages.

**Comment by atze09** [comment]
Hello Mike,
First of all thank you for the files, but unfortunately i cannot install them.
I get the error:
Collected errors:
- deb_extract: tmp/libsoxr_0.1.1-2_ar71xx.ipk: invalid magic
- pkg_init_from_file: Failed to extract control file from tmp/libsoxr_0.1.1-2_ar71xx.ipk.

I don't know how to proceed

**Comment by mikebrady** [comment]
Are you using the `opkg` utility to install them?

**Comment by atze09** [comment]
Yes

**Comment by mikebrady** [comment]
Let me look at this again over the weekend – I may have done something stupid. Meantime, could you do `$uname -a` and `$cat /etc/banner` on your 710N please?

**Comment by atze09** [comment]
root@OpenWrt:/# uname -a
Linux OpenWrt 3.18.20 #1 Fri Sep 4 21:55:57 CEST 2015 mips GNU/Linux

root@OpenWrt:/# cat /etc/banner

---

 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -**|     ||  |  |  ||   _||   _|
 |_____**||   **|___**|**|**||________||**|  |__**|
          |__| W I R E L E S S   F R E E D O M

---

 CHAOS CALMER (15.05, r46767)

---
- 1 1/2 oz Gin            Shake with a glassful
- 1/4 oz Triple Sec       of broken ice and pour
- 3/4 oz Lime Juice       unstrained into a goblet.
- 1 1/2 oz Orange Juice
- 1 tsp. Grenadine Syrup
  -----------------------------------------------------

**Comment by mikebrady** [comment]
Thanks for the info. The Chaos Calmer SDK I'm using is for r48246. I built the packages I sent you using the 'M' option ('M' for module, i believe). I've rebuilt them using the standard '*' option. They have slightly different file sizes, so let's hope they are more useful. Update – I've now sent the r46767 versions too.

**Comment by atze09** [comment]
Hello Mike,
This was my fault, i had a file transfer issue, after using winscp i can install both packages.
Now shairport-sync -V gives me the 2.6 answer.
And it works with synology audio station.
Thank you very much for your awesome support, you are the best!

Now i can replace my raspberrys with WR710:-)

Best regards,
Dominik

**Comment by mikebrady** [comment]
Great stuff.

**Comment by vaski666** [comment]
Hi Mike,

I would love to get a copy of the files you sent to atze09.
i have the same build and kernel as him

Edit: my email is vaski79"at"gmail.com
Br,

John A.

**Comment by mikebrady** [comment]
It might take me a while to regenerate it...

**Comment by vaski666** [comment]
Ok,  no stress at all. 
i will use the one i have  
I was going to use it with a logitech g930 and it seems it is not straight forward so i hoped that a newer version might help

**Comment by mikebrady** [comment]
Hi there John. Here is Shairport Sync 2.8.1 for r46767.

Regards
Mike

**Comment by hjhrwerv2423** [comment]
Hello Mike!
Can i get this files too? Thanks a lot!
my e-mail: vaslobas@gmail.com

I'am using router wl-500gp v1 https://wiki.openwrt.org/toh/asus/wl500gp

I have the same system as other guys in this topic.
`2.1.15-openssl-Avahi-ALSA-soxr

Linux OpenWrt 3.18.20 #1 Fri Sep 4 14:50:22 CEST 2015 mips GNU/Linux

 CHAOS CALMER (15.05, r46767)`
