### ISSUE TITLE
USB software power control?

### ISSUE THREAD

**Issue by bobbitchin** [mikebrady/shairport-sync-for-openwrt#15]
Wondering if this project also provides USB power control, or if that is even a possibility with this SOC?

My main issue with the DIR-505 is that the USB port only works with a powered USB hub attached.  I guess it works with the stock firmware, so I was wondering if they are controlling USB power through the firmware

**Comment by mikebrady** [comment]
Hi there. I'm afraid your question isn't really relevant to Shairport Sync. if you find a way of controlling the USB power, then you could add a command to turn it on before Shairport Sync starts playing, but I have no idea if there is such a command.

**Comment by gerrydoro** [comment]
I think that the power control should be set by the device itself, maybe from the OS/Kernel. This is OP but, what OS are you using on that device?

**Comment by mikebrady** [comment]
Closing this. Feel free to open a new issue if necessary.
