### ISSUE TITLE
The Airplay Device is not compatible with this version of itunes

### ISSUE THREAD

**Issue by atze09** [mikebrady/shairport-sync-for-openwrt#16]
Hello Mike,
I have installed your Version on my wr710 routers.
Now i realized that if i want to play on multiple wr710 devices through itunes i get the above error message. (The Airplay Device is not compatible with this version of itunes)
What is my fault?
Hope you can help me.
Thank you.
Best Regards,
Dominik

**Comment by mikebrady** [comment]
Hi Dominik. Can you tell me which version of iTunes you are using and also which version of Shairport Sync? For Shairport Sync's version, enter `shairport-sync -V`.

**Comment by atze09** [comment]
I have updated to the latest itues version 12.4.1.6, but the fafilure still exists.
The shairport-sync version is "2.6-openssl-Avahi-ALSA-soxr-metadata".
Thank you in advance.
I can play each plaer on his own.

**Comment by mikebrady** [comment]
Hi Dominik. Thanks for the update. It's a mystery to me – right now, I listening to iTunes 12.4.1.6 playing to a WR710N running a development version of OpenWrt: "BARRIER BREAKER (Barrier Breaker, r45951)", and Shairport Sync "2.8.4-OpenSSL-Avahi-ALSA-soxr-metadata", while simultaneously playing to a C.H.I.P running the same version of Shairport Sync with no problems at all.

I did see a number of references to the error message, though not related to Shairport Sync, for example: https://discussions.apple.com/thread/4675327?tstart=0.

Back to Shairport Sync – there are bug fixes between 2.6.X and 2.8.4, worth updating for, but AFAIR nothing to cause this problem.

**Comment by atze09** [comment]
Thank you for your quick reply.
I can listen to more CHIP devices and 1 WR710, but as soon as i start a second wr710, i get this error.
How can i upgrade the shairport version on WR710 and CHIP?

**Comment by atze09** [comment]
I did a backup of OpenWRT and restored it on my second and third device, is this the problem?

**Comment by mikebrady** [comment]
That should not be a problem as long as you give them different service names. Did you do that?

**Comment by atze09** [comment]
Yes i gave them seperate names.
Now i tried to do a factory reset and did a reconfiguration and was successful.
You can close this.
Thank you!

**Comment by mikebrady** [comment]
Thanks for the update. What do you think the issues was caused by?

**Comment by atze09** [comment]
Hm i thought i had the solution, but same still same issue here, maybe i will change to more CHIP's and sell the WR710..

**Comment by mikebrady** [comment]
Hmm. I only have one 710, so I can't check it out, I'm afraid. It's very strange.
