### ISSUE TITLE
 [alsa-lib] unable to open timer + unable to initialize poll_fd

### ISSUE THREAD

**Issue by gerrydoro** [mikebrady/shairport-sync-for-openwrt#17]
Just installed OpenWRT trunk on my HG553, then I Installed all the kmods for usb support and audio support and finally I installed shairport-sync but something gone wrong...

root@HG553:# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@HG553:# alsactl init
Found hardware: "USB-Audio" "USB Mixer" "USB0d8c:013c" "" ""
Hardware is initialized using a generic method
root@HG553:# shairport-sync
Successful Startup
ALSA lib pcm_direct.c:1421:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1183:(snd_pcm_dmix_open) unable to initialize poll_fd
ALSA lib pcm_direct.c:1421:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1183:(snd_pcm_dmix_open) unable to initialize poll_fd
ALSA lib pcm_direct.c:1421:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1183:(snd_pcm_dmix_open) unable to initialize poll_fd
ALSA lib pcm_direct.c:1421:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
...
...

Also shairport-sync won't start at boot, even with
/etc/init.d/shairport-sync enable
/etc/init.d/shairport-sync start

> Sorry for my bad english

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. I'm afraid I don't really know what is missing from your setup. I suggest installing `alsamixer` or `aplay` to see if you can use the audio system separately from Shairport Sync. In this way, you can determine if the problem lies with Shairport Sync or with your system.

Just for information, what version of Shairport Sync is running. (Enter `shairport-sync -V` and note the result.

**Comment by gerrydoro** [comment]
Hi, probably there was a problem with the kernel in that version of OpenWRT. Backing up to Chaos Calmer everything works fine. Sorry for the issue.

**Comment by mikebrady** [comment]
Thanks for the update.
