### ISSUE TITLE
OpenWRT Version

### ISSUE THREAD

**Issue by 8times4** [mikebrady/shairport-sync-for-openwrt#18]
Hey mikebrady, 

I love the work you did with shairport-sync, but I'd like to ask if you're planning to ever bump the version on Openwrt version? Or I can simply just install it similar how I'd do on raspbian? 

Thanks, 
Mark

**Comment by mikebrady** [comment]
Thanks for the post, Mark. 

The latest version in OpenWrt is 3.3.5, only one point behind the current release. Building it for OpenWrt is quite tricky. You either need to have the build tools – compiler etc. on your OpenWrt system, which is very unusual. However, if that is your situation, then I imagine that building it is fairly straightforward.

Otherwise, and more usually, you need to cross compile it – see the OpenWrt website for information on that. In that case, it's not really similar to building it for Raspbian.

**Comment by 8times4** [comment]
Oh Okay, thank you very much! :)
bit off topic here..but,
One more thing, I seem to fail in getting this to work.
I installed the `openssl` package on my rpi4 openwrt, installed the `kmod sound` package, and all other dependecies, but I cannot seem to get it running properly, since the `-d `option does not work. 
I also can't get any signal out on the jack plug, though I'm trying to force it via `audio_pwm_mode=2 `in config.txt
I get a few logs when running it via 'shairport-sync' cmd. 
`ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM default
`

**Comment by mikebrady** [comment]
I’m afraid I’m not really au fait with running OpenWrt on a Pi. I tried it many years ago and found it frustrating. I don’t know if it has drivers for the built-in sound facilities.

Shairport Sync doesn’t need to be able to daemonise (thus it doesn’t need to be able to implement the `-d` option) in OpenWrt. The automatic launch system looks after daemonising the program itself.

**Comment by 8times4** [comment]
Yeah, it's frustrating, I'm rather focusing on getting it to work on Docker, that's running on OpenWRT. Thank you for your support, and thanks again for what you did with Shairport-sync!
