### ISSUE TITLE
Libsoxr not available on Openwrt, causing build failure

### ISSUE THREAD

**Issue by ericwongcm** [mikebrady/shairport-sync-for-openwrt#3]
I don't see Libsoxr available in Openwrt, that means if I use your new makefile, the build will fail because Libsoxr is not found.

I found your post that you maybe able to build Libsoxr for Openwrt but I don't see any information/instruction how you actually managed to build Libsoxr for Openwrt.
http://sourceforge.net/p/soxr/discussion/general/thread/1f36d0b2/?limit=50

I would suggest you to include the Libsoxr package for Openwrt in your shairport-sync package or similar. So that others like me don't have to figure out how to include Libsoxr package for Openwrt.

**Comment by mikebrady** [comment]
Hi Eric. Libsoxr is indeed in the OpenWrt trunk package feed: https://github.com/openwrt/packages/tree/master/libs/libsoxr
You might need to do something like ./scripts/feeds update -a and then something like ./scripts/feeds install libsoxr. (I'm not at a computer right now...)

**Comment by ericwongcm** [comment]
Thanks... I tried but can't build libsoxr.
Did you manage to build libsoxr using the OpenWrt trunk package link you posted?

FYI, I am using Attitude Adjustment. I think you are using Barrier Breaker?
I think this error should be reported back to OpenWrt trunk package together with your results.

I get the error below.

make[3]: Entering directory `/home/openwrt/openwrt/attitude_adjustment/package/libsoxr'
CFLAGS="-Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/usr/lib -L/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/lib -L/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/usr/lib -L/home/openwrt/openwrt/attitude_adjustment/staging_dir/toolchain-mipsel_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib " make  -j1 -C /home/openwrt/openwrt/attitude_adjustment/build_dir/target-mipsel_r2_uClibc-0.9.33.2/libsoxr-0.1.1/. AR=mipsel-openwrt-linux-uclibc-ar AS="mipsel-openwrt-linux-uclibc-gcc -c -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float" LD=mipsel-openwrt-linux-uclibc-ld NM=mipsel-openwrt-linux-uclibc-nm CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB=mipsel-openwrt-linux-uclibc-ranlib STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CROSS="mipsel-openwrt-linux-uclibc-" ARCH="mipsel" ;
make[4]: Entering directory`/home/openwrt/openwrt/attitude_adjustment/build_dir/target-mipsel_r2_uClibc-0.9.33.2/libsoxr-0.1.1'
make[4]: **\* No targets specified and no makefile found.  Stop.
make[4]: Leaving directory `/home/openwrt/openwrt/attitude_adjustment/build_dir/target-mipsel_r2_uClibc-0.9.33.2/libsoxr-0.1.1'
make[3]: *** [/home/openwrt/openwrt/attitude_adjustment/build_dir/target-mipsel_r2_uClibc-0.9.33.2/libsoxr-0.1.1/.built] Error 2
make[3]: Leaving directory`/home/openwrt/openwrt/attitude_adjustment/package/libsoxr'
make[2]: **\* [package/libsoxr/compile] Error 2
make[2]: Leaving directory `/home/openwrt/openwrt/attitude_adjustment'
make[1]: *** [/home/openwrt/openwrt/attitude_adjustment/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory`/home/openwrt/openwrt/attitude_adjustment'
make: **\* [world] Error 2

**Comment by ericwongcm** [comment]
I also notice libsoxr is not selected when Shairport-sync is selected. I suspect there is maybe some problem with your makefile. Maybe because you have two line for dependency instead of one, i.e. line 23 and line 47.

You should consider using the makefile and associated init.d/config file structure I had previously submitted a pull request. It is now labelled 2.0 branch.

I have tried adding libsoxr dependency in my makefile and it would make libsoxr selected when Shairport-sync is selected.

FYI, I don't have PKG_BUILD_PARALLEL in my makefile because parallel compilation is known to cause problems for Openwrt. I am not sure if this problem is solved yet or not.
See line 21-27: http://www.gargoyle-router.com/gargoyle/projects/gargoyle/repository/revisions/master/entry/build.sh

**Comment by mikebrady** [comment]
Hi Eric. Your last three posts raise a number of issues. Let me address them here:
1. Shairport Sync builds cleanly against OpenWrt trunk. Libsoxr is in the packages collection (It was myself that submitted it, BTW) and is selected automatically by the Shairport Sync.
2. Libsoxr is not one of the standard packages for Attitude Adjustment, but it is easy to add. You copy it from the OpenWrt trunk package repository of Attitude Adjustment's package folder as follows: Say you have your Attitude Adjustment build system at ~/aa/openwrt. Using git, clone the OpenWrt trunk package repository to a separate directory – call it ~/tp for example – and copy the libsoxr folder from ~/tp/libs/ to  ~/aa/openwrt/package/. Then touch the folder: touch ~/aa/openwrt/package/libsoxr and do a make menuconfig etc. By following the regular instructions here, you can go on to build Shairport Sync in Attitude Adjustment with libsoxr support – I've just done so. Libsoxr was indeed correctly selected.
3. I haven't had any particular problems with parallel building of OpenWrt. The only thing to watch for is multiple compilation threads (or processes) running out of memory. To avoid this, simply specify the amount of parallelism to be the number of cores plus 1. For my 8-core machine, I use make -j 9.
4. Lines 23 and 47 of the Makefile are both necessary: Line 23 specifies the packages that should be installed in the build system if the shairport-sync-for-openwrt package is installed (this feature only works for packages that are part of the package feed – it doesn't work for packages you add to the ~/aa/openwrt/package directory). Line 47 specifies which libraries must be built before shairport-sync is built; in general, this may be a subset of the packages installed.

I hope this helps. What architecture are you building for?

**Comment by ericwongcm** [comment]
1) Did you try to build Libsoxr on Attitude Adjustment?
Maybe it build for Trunk (CC) but not AA?
Or are you using BB? I know Trunk is renamed to CC now.

2) Well, I have manually downloaded the Libsoxr package from OpenWrt trunk package repository and put it in the Openwrt package folder. I also do make menuconfig and I can see libsoxr in menuconfig. I have done this for other packages before and I believe my procedure should be correct.

4) I manually added the package (copy/paste), that is probably why I think line 23 is redundant.

5) I am building for RAMIPS on AA. Could this be the reason it failed? Or I should do a full clean (make dirclean) and rebuild?

**Comment by mikebrady** [comment]
1. Yes, in response to your post, today I built it on AA. So it builds on trunk and on AA.
2. Yep, that sounds like what I was describing.
3. Correct – line 23 only has significance if/when the package is part of the package repository.
4. Thanks – I'll try it on that architecture tomorrow. It should compile, but yes, if I was you, I would do a full clean and rebuild.

**Comment by ericwongcm** [comment]
I have tried make dirclean. Same result.

Will try to download latest version of AA and feed tomorrow to rebuild and get back to you.

**Comment by ericwongcm** [comment]
I have downloaded latest AA, updated feeds, manually added Shairport-sync, libsoxr and build.
The error output is exactly the same as what I posted before,.

The default feeds for AA doesn't use the same feed as trunk, so I need to manually add libsoxr.

FYI, I am building for rt305x, RAMIPS if you are going to reproduce the error.
If you tell me what architecture you were able to successfully build Shairport-sync with libsoxr. I can try that to make sure I can compile for that architecture and the able to confirm if the problem is RAMIPS specific.

**Comment by mikebrady** [comment]
I was successful in building for the rt305x just now. I wonder if there isn't something wrong with your Linux system – maybe short of some resource: RAM/Disk Space/Swap? Here are details of my setup and procedures:

My system is Ubuntu 14.04 LTS running in VMware 6.0.4 on a Mac Pro:
- Ubuntu 14.04 LTS, VMware 6.0.4 2 GB RAM, 8 cores, 100 GB Hard Disk
- 25.8 GB of 104.5 GB in use. (Disk Usage Analyser)
- 1.9Gib Memory 1021.0 MiB Swap (System Monitor)

```
$uname -a
Linux ubuntu 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$sudo du -sh /
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1      102049120 25187876  71654412  27% /
none                   4        0         4   0% /sys/fs/cgroup
udev             1010560        4   1010556   1% /dev
tmpfs             204268     1148    203120   1% /run
none                5120        0      5120   0% /run/lock
none             1021336      152   1021184   1% /run/shm
none              102400       64    102336   1% /run/user
```

Following build advice from:
http://wiki.openwrt.org/doc/howto/buildroot.exigence

http://wiki.openwrt.org/doc/howto/buildroot.exigence#downloading.sources

Here are the commands I executed:

```
$git clone git://git.openwrt.org/12.09/openwrt.git attitude-adjustment
$cd attitude-adjustment
$./scripts/feeds update -a
```

Next, I manually copied the `libsoxr` folder into `attitude-adjustment/package`. Then:

```
$touch package/libsoxr
$make menuconfig
```

with the following choices:

```
  Target System (Ralink RT288x/RT3xxx)
  Subtarget (RT305x based boards)

  Libraries -->
    <*> libsoxr........................................ The SoX Resampler library 
```

Save & exit, then a timed parallel-enabled make:

```
$time(make -j 9)

real    15m5.841s
user    42m30.989s
sys 17m14.281s
```

**Comment by ericwongcm** [comment]
Thanks for your test. I still have not figured out what is wrong with my setup yet..

I am using Ubuntu 12.04 and I have not updated anything since it was configured.
I suspect it could be related to my outdated software.
I will try a new install of Ubuntu when I get to it and see what happens.

I believe I have sufficient disk/ram/swap space.

**Comment by ericwongcm** [comment]
I am able to build libsoxr now after this patch
https://github.com/openwrt/packages/commit/5c7c791a7a09aded76d527ce368b09d15ac3caf5

**Comment by mikebrady** [comment]
That's good news. I'm still puzzled why it was happening and why this patch fixed it. Can you say what kind of machine your development host is?

**Comment by ericwongcm** [comment]
I don't think the problem is related to hardware. In fact, I was actually using an Intel Core 2, 3Ghz to build this previously. Right now, I am using the same hdd, holding the same OS on an AMD Athlon 64 x2 4600+ to build this successfully.

I am using Ubuntu 12.04, 32bit. You can consider this installation almost the same as if you had just installed Ubuntu 12.04 32bit to any computer plus the dependency packages required to build Openwrt ROM. I didn't update the packages since this was installed 1-2 years ago in case it break something... as I only use this OS to build Openwrt ROM.

FYI, GRUB says kernel 3.2.0-29-generic-pae

**Comment by mikebrady** [comment]
Thanks. If I get a chance, I'll try to build it on a VM.

**Comment by ericwongcm** [comment]
Up to you.. I should stress the fact that I am using the exact same installation in both computer I described earlier, I simply swap the hdd out to another machine for convenience because I had traveled to another location.

**Comment by steveharman** [comment]
Hi Mike,

I'm in a similar position to @ericwongcm - I'm using barrier Breaker on a TP-LINK WDR 3600 (and built OpenWrt fine on my Mac).

Your instructions at https://github.com/mikebrady/shairport-sync-for-openwrt have been perfect so far, yet even after updating my feeds - when I execute ./scripts/feeds install libavahi alsa-lib libdaemon libpopt libsoxr alsa-utils htop - I get:

WARNING: No feed for package 'libsoxr' found, maybe it's already part of the standard packages?

I dug around but couldn't get much further so decided to try a make anyway.  Perhaps unsurprisingly it eventually gave up with:

configure: error: soxr support requested but libsoxr not found!

Do you have any suggestions at all please?  Really excited about getting Shairport-Sync up & running.

Cheers,

Steve

**Comment by mikebrady** [comment]
Hi Steve. Thanks for your interest in Shairport Sync. The OpenWrt package for Shairport Sync only works with trunk – it relies on `libsoxr` and also another package called `libconfig`, which, while part of Barrier Breaker, isn't fully connected up so that the linker can find it. If you will bear with me for a short while, I'll post a package specifically for Barrier Breaker. It will omit `libsoxr` – which the WDR 3600 probably wouldn't have the horsepower to run anyway – and it works around the `libconfig` issue.

**Comment by steveharman** [comment]
Hi Mike,

That would be great, thanks.

I'm not tied to Barrier Breaker if you think that building from Chaos Calmer might help, I'll gladly try that.

Thanks again,

Steve

**Comment by mikebrady** [comment]
Hi Steve, and hello again @ericwongcm . I've made up a new OpenWrt package specifically for the Attitude Adjustment (AA) and Barrier Breaker (BB) builds, and it builds the absolutely latest version of Shairport Sync. It's at https://github.com/mikebrady/shairport-sync-for-openwrt/tree/attitude-adjustment.

(Eric, a good few things have changed, most especially the use of a `/etc/shairport-sync.conf` file for settings and there are some extra features, e.g. passwords.)

The package definitely compiles on AA and on BB and it definitely runs properly on BB – I don't have a device that I can readily install AA onto right now. I'd be interested in reports of your experiences, thanks.

**Comment by steveharman** [comment]
Hi Mike,

That's great, thanks a million,

The build completed without error and now I have my images:

openwrt-ar71xx-generic-tl-wdr3600-v1-squashfs-factory.bin  
openwrt-ar71xx-generic-tl-wdr3600-v1-squashfs-sysupgrade.bin

Currently I have Barrier Breaker on the router (without Shairport Sync) - would I be best to flash the factory or sysupgrade binaries?

Thanks again for your help with this.

Regards,

Steve

-----Original Message-----

**Comment by mikebrady** [comment]
Hi Steve. I don’t have experience with the WDR3600, but I do with the TP-Link 710N and, once I have another OpenWrt on it, I just use the sysupgrade method:

http://wiki.openwrt.org/doc/howto/generic.sysupgrade

As every, do at your own risk, etc.

**Comment by steveharman** [comment]
Hi Mike,

Great, I'll give that a spin first.

Do I need to do anything to launch the shairport-sync service?  I notice your instructions say that if I had a soundcard the service would come up automatically, but I don't have one on the router.

Regards,

Steve

-----Original Message-----

**Comment by mikebrady** [comment]
The installer installs a launch script, so it'll try to launch Shairport Sync on startup; however, without a sound card it will abort. It might put out an error message first... Once you have a sound card, you'll need to edit `/etc/shairport-sync.conf` to suit it. You can use `alsamixer` (part of `alsa-utils`) to explore the sound card's properties, name, etc.

**Comment by steveharman** [comment]
Hi Mike,

Ah right, I'll need to look into a soundcard (any recommendations ;) ?)  Didn't realize it was mandatory. 

Sorry, I know that sounds daft but I wondered if it was only a requirement for audio playback on the router, rather than if I was just using the router with shairport-sync for audio distribution.

Regards,

Steve

-----Original Message-----

**Comment by mikebrady** [comment]
Hmm. You could spend a heap of money on a fancy USB DAC, but, for experimentation, a cheap PC-compatible USB "Soundcard" will work. Typically they cost about $5 and have a rather restricted (~30 dB) range of volume. They are a bit noisy in audio terms, but they are really cheap.

http://www.amazon.com/External-Adapter-Desktop-Notebook-Laptop/dp/B001MW92AE

If you liked the results, you could graduate to something classier. I've been using a Topping TP30, which combines a USB DAC and a reasonably good amplifier for not too much money. But you could spend a ton of money.

Also, I'm not too sure of the second part of your comment. What Shairport Sync does is provide the software for the router to act as a remote speaker for, say, iTunes. The audio that it gets from iTunes is routed to a connected audio device. OTOH, if you're taking the audio feed into a unix pipe for further processing, then of course you might not need a sound card. I hope that clarifies it a bit.

**Comment by steveharman** [comment]
Thanks for all your help Mike, I can now report a successful build, flash and installation of Shairport Sync - the audio quality even sounds great with a £2 ($3) USB eBay sound card!  :-)

So my only remaining question is how to USE Shairport Sync, or more specifically in a multi-room capacity.  At present I can see ShairPort-Sync from an iOS device and iTunes, but there's a gap in my understanding of how to play music through multiple airplay "speakers" in separate locations at the same time.

Thanks again for all your work with this project - great job.

Steve

**Comment by mikebrady** [comment]
That's good news – well done. And this is on the WDR3600, right?

So, the idea is that with iTunes you can direct the output to multiple AirPlay devices simultaneously – say an AirPort Express and a Shairport Sync device, or maybe just the computer's speakers and a Shairport Sync device. Because Shairport Sync stays in sync with the source, the audio coming from it and all simultaneously-connected devices will stay in sync. Here's a picture of iTunes with the computer's own speakers and a Shairport Sync-connected set of speakers (on the other side of my room) selected to play simultaneously. The padlock icon is because I have a password set on it.
![multiple](https://cloud.githubusercontent.com/assets/4265913/8379345/461c507e-1c17-11e5-8973-06271c3e6cf6.jpg)
You can't connect multiple AirPlay speakers to an iOS source (well, to be exact, it's not supported by iOS), just to iTunes.
You can connect to an AirPlay device via the Mac's System Preferences, but it's a bit awkward. IMHO AirPlay works best for playing iTunes or playing Quicktime movies. I hope this helps.

**Comment by steveharman** [comment]
Great, got it Mike - thanks.  And yes to the WDR3600.

Do you ever foresee a time when Shairplay Sync could act as a "relay" to other Airplay speakers - such that iOS devices would see a single "Shairplay Sync for OpenWRT" as the target and Shairport Sync would distribute the stream to multiple Airplay receivers?

Cheers,

Steve

**Comment by mikebrady** [comment]
Honestly I haven't thought about it too much, wondering about what its use case might be...

**Comment by steveharman** [comment]
Basically for multi-room streaming from iOS devices (getting around the current limitation of no multiple-speaker support from iOS devices).  

Eg; if we had an Airplay speaker in the kitchen, one in the dining room, one in another room - Spotify could be streamed from an iPad to Shairport Sync, with Shairport Sync handling distribution of the stream to the various speakers / rooms.  At the moment we'd have to fire up iTunes on a computer to achieve multi-room.

It would make Shairport Sync unique.  ;-)

**Comment by mikebrady** [comment]
Interesting all right – I'll have a think about it.

**Comment by steveharman** [comment]
If you decided to try something Mike I'd be happy yo help with testing. (It's what I do....).  

We have a few Airplay speakers knocking about too.
