### ISSUE TITLE
Timeout=0 doesn't work on TP-Link TL-WR710N

### ISSUE THREAD

**Issue by b-fitzpatrick** [mikebrady/shairport-sync-for-openwrt#6]
I was trying to use the "-t 0" option to allow playback to be interrupted.  Using -vv, I could see that config.timeout was being set to 0, but when I tried to interrupt, it would return the busy signal and output "Already playing."

I was originally compiling 2.1.8.  I built the same code (copied from the dl folder) on my Raspberry Pi, and it worked as expected.  I then moved to 2.1.9 with the same results.

I added a debug output right before the if statement in rtsp.c that output the value of config.timeout, and it printed 0, but the if condition still evaluated false.  Next, I added a line (config.timeout = 0;) immediately proceeding the if statement, and it then works as expected.

I'm a complete novice with C and OpenWRT, but hopefully you have an idea of what's happening.

**Comment by mikebrady** [comment]
Thanks for your report. Let me check this out over the weekend.

**Comment by mikebrady** [comment]
I found an issue that _might_ be causing this problem. The timeout value was defined as a 64-bit integer but treated as a (32-bit) integer when a value was being assigned to it and when it was printed by that debug message... Fixed in 2.1.10. Could you try it out?

**Comment by b-fitzpatrick** [comment]
That fixed it.  Thanks, and thanks for Shairport-sync and the OpenWRT package.
