### ISSUE TITLE
Please upload shairport-sync_2.x.x_ar71xx.ipk

### ISSUE THREAD

**Issue by probonopd** [mikebrady/shairport-sync-for-openwrt#7]
Please upload shairport-sync_2.x.x_ar71xx.ipk
Thanks

**Comment by mikebrady** [comment]
I am working towards adding a shairport-sync package to the OpenWrt trunk. Hopefully that will result in packages being automatically built.

**Comment by probonopd** [comment]
That would be cool. Thank you!
